### ISSUE TITLE
A couple of things...

### ISSUE THREAD

**Issue by davidtew** [bobrocke/grav-theme-materialize#1]
1) right now a Whoops \ Exception \ ErrorException (E_ERROR) is showing upon clicking the 'Demo' link http://materialize.bobrockefeller.com/  on the  page: http://getgrav.org/downloads/themes
2) when I tried a search (in the theme's blog section), any results page showed small photo displaced, it seemed to me.

**Comment by bobrocke** [comment]
1) I think that's fixed now. See if I'm right?

2) Yep. Bug. I'll get into that. I think I have a CSS problem on that page.

**Comment by davidtew** [comment]
Yes, 1) (Demo link) is showing fine.  Thanks

On 29 April 2015 at 18:21, Bob Rockefeller <notifications@github.com> wrote:

> 1) I think that's fixed now. See if I'm right?
>
> 2) Yep. Bug. I'll get into that. I think I have a CSS problem on that page.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bobrocke/grav-theme-materialize/issues/1#issuecomment-97531271>
> .
>



-- 
Regards
David Tew
*01522 704293*

**Comment by bobrocke** [comment]
Fixed the page layout on search result pages.
