### ISSUE TITLE
Active Materialize Theme causes displace in Grav admin panel 

### ISSUE THREAD

**Issue by axel-rank** [bobrocke/grav-theme-materialize#3]
Installed and activated materialize theme -->result:
![screenshot](https://cloud.githubusercontent.com/assets/12480617/9964361/22898068-5e30-11e5-8054-03d2e1e3e684.png)
![screenshot2](https://cloud.githubusercontent.com/assets/12480617/9964365/283dc2b2-5e30-11e5-9071-b97ee7ac998c.png)

**Comment by bobrocke** [comment]
I've seen that on occasion (usually right after a Grav update), too. And I think in other themes as well.

Try refreshing the browser's cache and see what you get.

**Comment by axel-rank** [comment]
No change. Tested in Firefox, Opera. Cleare all cache

**Comment by bobrocke** [comment]
Clear Grav's cache and then the browser cache. Widen and narrow the viewport to force the Admin's responsive CSS to adjust the sidebar. For me, the glitch has always cleared itself and I've not be able replicate the exact steps to get there.

You have the most recent Grav and Admin, I assume?

**Comment by axel-rank** [comment]
Grav, admin up to date

**Comment by bobrocke** [comment]
Fixed with changes to the Materializer plug-in v1.3.2.
