### ISSUE TITLE
Question: Gallery & slideshow

### ISSUE THREAD

**Issue by basti1dr** [bobrocke/grav-theme-materialize#4]
Hi, 

Have you any plans to include and a gallery and a slideshow (per articles) ?

EDIT: maybe this part is already available http://materializecss.com/media.html

Bastien

**Comment by bobrocke** [comment]
I haven't given this much thought, assuming that one could add whatever code one needed. But maybe I'll find a little time to experiment...

**Comment by basti1dr** [comment]
Okay, I'll keep this in mind and make a pull request for integrate a gallery

**Comment by basti1dr** [comment]
I close this it was just a question
