### ISSUE TITLE
Header/Main/Footer

### ISSUE THREAD

**Issue by mttmccb** [bobrocke/grav-theme-materialize#5]
Could this updated? This would make it easier to do a sticky footer http://materializecss.com/footer.html

**Comment by bobrocke** [comment]
@mttmccb Updated in what way?

**Comment by mttmccb** [comment]
I can't remember now, I think the main tag might have been missing, I'll put it in a pull request

**Comment by bobrocke** [comment]
Thanks!

**Comment by UdoKifferbrehl** [comment]
Hi, any updates here? 
Is it possible to hide the footer?

**Comment by bobrocke** [comment]
Is that was it needed? A way to hide the footer? It would probably be easier to do that with CSS in a local customization. No?

**Comment by mttmccb** [comment]
Sorry, never got around to doing the pull request :) it's nothing to do with hiding the footer

**Comment by bobrocke** [comment]
PRs gladly accepted! :)
