### ISSUE TITLE
how does grav make using materialize css easier

### ISSUE THREAD

**Issue by 4evermaat** [bobrocke/grav-theme-materialize#6]
I'm somewhat confused as to how to implement this theme.  Do I still have to code the different aspects of materialize css framework?  Or do I use shortcodes to just insert the asset that I want into the markdown?

I'm confused because I want to be able to build a website but not have to copy js/css for each slider or animation that I want to do.

**Comment by bobrocke** [comment]
The Materialize Theme depends on the Materializer Plug-in:

https://github.com/bobrocke/grav-plugin-materializer

If that is installed, all the materialcss framework is available.

**Comment by 4evermaat** [comment]
I understand that.  But basically we still have to know how to use materialize css?  
Like there are no shortcodes to implement the various different assets of materializecss?  I'm talking about being able to create pages via grav admin panel.

I'm sorry if the original post was not clear.

**Comment by bobrocke** [comment]
Another source of information is the Materialize site itself. It will tell you what classes to use to get what styling:

http://materializecss.com/about.html

**Comment by 4evermaat** [comment]
I would like to see some sort of shortcode so that I can call an asset at will and switch on/off parameters without having to copy the js/css

**Comment by bobrocke** [comment]
You don't have to copy anything. Just apply classes to get the look you want. Dig into the theme's source code to see how the theme has applied Materialize classes.
